// <auto-generated />
using System;
using DoAnQuanLyTienGui.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnQuanLyTienGui.Migrations
{
    [DbContext(typeof(QLTGDbcontext))]
    [Migration("20260311160408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.GiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoaiGiaoDichId")
                        .HasColumnType("int");

                    b.Property<string>("MaGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGD")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoTietKiemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiGiaoDichId");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("SoTietKiemId");

                    b.ToTable("GiaoDich");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.LoaiGiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiGiaoDich");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.SoTietKiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int>("KyHan")
                        .HasColumnType("int");

                    b.Property<decimal>("LaiSuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayMoSo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("SoTietKiem");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.GiaoDich", b =>
                {
                    b.HasOne("DoAnQuanLyTienGui.Data.LoaiGiaoDich", "LoaiGiaoDich")
                        .WithMany("GiaoDich")
                        .HasForeignKey("LoaiGiaoDichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.NhanVien", "NhanVien")
                        .WithMany("GiaoDich")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnQuanLyTienGui.Data.SoTietKiem", "SoTietKiem")
                        .WithMany("GiaoDich")
                        .HasForeignKey("SoTietKiemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiGiaoDich");

                    b.Navigation("NhanVien");

                    b.Navigation("SoTietKiem");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.SoTietKiem", b =>
                {
                    b.HasOne("DoAnQuanLyTienGui.Data.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.LoaiGiaoDich", b =>
                {
                    b.Navigation("GiaoDich");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.NhanVien", b =>
                {
                    b.Navigation("GiaoDich");
                });

            modelBuilder.Entity("DoAnQuanLyTienGui.Data.SoTietKiem", b =>
                {
                    b.Navigation("GiaoDich");
                });
#pragma warning restore 612, 618
        }
    }
}
